title: iottt
email: looksgoood12@gmail.com
description: |
  회사원이 아닌 개발자가 되보자.
baseurl: ''
url: 'https://iottt.github.io'
timezone: Asia/Seoul 

repository: iottt/looksgoood.github.io

permalink: /:year/:month/:day/:title/

excerpt_separator: <!--more-->

markdown: kramdown

krandown:
  input: GFM
  highlighter: rouge

plugins:
  - jekyll-paginate

paginate: 5
paginate_path: '/page/:num/'

collections:
  authors:
    output: true
    permalink: /authors/:path/
  tags:
    output: true
    permalink: /tags/:path/

defaults:
  - scope:
      path: ''
      type: authors
    values:
      layout: author
  - scope:
      path: ''
      type: tags
    values:
      layout: tag

exclude: [README.md, Gemfile, Gemfile.lock]

keep_files: [assets, files]
github: [metadata]
# iolo's custom
author: looksgoood12@gmail.com
image: '/assets/images/default_blog_cover.jpg'
asset_url: /assets
#asset_url: //meta-kage.kakaocdn.net/dn/osa/blog/assets
#asset_url: //t1.daumcdn.net/osa/blog/assets
google_analytics:
  ua: 'UA-72007721-1'
facebook:
  app_id: '1204347326263800'
  username: looksgoood
google_plus:
  username: looksgoood12
github_url:
  username: looksgoood
